import Head from "next/head";
export default function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid h-[100vh] place-items-center">
        <main className="bg-white rounded shadow-2xl flex flex-col h-full overflow-y-auto position relative w-full md:h-[90vh] sm:w-[640px]">
          {children}
        </main>
      </div>
    </>
  );
}
